# Generated by Django 3.1 on 2020-09-29 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_userseminar_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
