# Generated by Django 3.1 on 2020-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_auto_20200930_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userseminar',
            name='joined_at',
        ),
        migrations.AlterField(
            model_name='seminar',
            name='capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='role',
            field=models.CharField(blank=True, choices=[('participant', 'participant'), ('instructor', 'instructor')], db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='userseminar',
            constraint=models.UniqueConstraint(fields=('user', 'seminar'), name='userseminar_unique'),
        ),
    ]
