# Generated by Django 3.1 on 2020-09-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200927_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='role',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
