# Generated by Django 3.1 on 2020-09-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200927_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
