# Generated by Django 3.1 on 2020-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200928_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='year',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
