# Generated by Django 3.1 on 2020-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200929_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
